// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.639
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Layout() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"\"><head><title>Contact App</title><link rel=\"stylesheet\" href=\"https://unpkg.com/missing.css@1.1.1\"><link rel=\"stylesheet\" href=\"/static/site.css\"><script src=\"/static/js/htmx-1.9.10.min.js\"></script><script src=\"/static/js/response-targets.js\"></script><script src=\"/static/js/hyperscript-0.9.12.min.js\"></script><script src=\"/static/js/rsjs-menu.js\" type=\"module\"></script><script src=\"/static/js/superadmin.js\"></script><script src=\"/static/js/sweetconfirm.js\"></script><script defer src=\"https://unpkg.com/alpinejs@3/dist/cdn.min.js\"></script><script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script></head><body hx-boost=\"true\" hx-ext=\"response-targets\"><main><header><h1><span class=\"all-caps\">contacts.app</span> <sub-title>A Demo Contacts Application</sub-title></h1></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, flash := range getFlash(ctx) {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flash\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(flash)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/hypermedia/web/view/layout/layout.templ`, Line: 30, Col: 38}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// logging, done in chrome console:
// monitorEvents(document.getElementById("some-element"));

// for cdn
//<script src="https://unpkg.com/htmx.org@1.9.10"
//        integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC"
//       crossorigin="anonymous"></script>
//<script src="https://unpkg.com/hyperscript.org@0.9.12"></script>

// debug to listen for event:
// document.addEventListener('DOMContentLoaded', (event) => {
//     document.body.addEventListener('confirmed', function(e) {
//         console.log('Confirmed event caught!', e.target);
//     }, true);
// });
